name: To run diff commands in git actions

on:
  workflow_dispatch

jobs:
    new-job:
      runs-on: ubuntu-latest
      steps:
      - name: Grouping
        run: |
             echo "::grouping:: Grouped Messages"
             echo "msg1"
             echo "msg2"
             echo "msg3"
             echo "::endgroup::"
