name: Repo-Dispatch-Testing

on:
   repository_dispatch:
     types: [my-event]

jobs:
 new-job: 
  runs-on: ubuntu-latest
  steps:
    - name: Checking out the code
      uses: actions/checkout@v4 

    - name: Checking Which Event 
      run: echo " The Event is ${{github.event.action}} "
