name: This is to learn how to use repository-dispatch

on:
  repository_dispatch:
    types: [webhook]

jobs:
  running-repodispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Printing the event name
        run: echo "The GitHub event is ${{ github.event_name }}"

      - name: Trigger repository dispatch
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $MY_PAT" \
            https://api.github.com/repos/ammararsiwala/Github-Examples/dispatches \
            -d '{"event_type":"webhook"}'
