name: This is a workflow to test env variables

on:
 workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

     - name: Trying to add a value
       run: |
            echo "MY_NEW=hello" >> $GITHUB_ENV

     - name: Printing that value
       run: | 
           echo "the value stored in the file is $MY_NEW"
    
